const RECIPES = [
  {
    id: 1,
    category: "frokost",
    subcategory: "frokost",
    title: "Lune havrepannekaker",
    description: "Myke pannekaker med havre, banan og et lite hint av kanel.",
    time: "25 min",
    servings: "2 personer",
    difficulty: "Enkel",
    ingredients: [
      "2 modne bananer",
      "2 egg",
      "1,5 dl havregryn",
      "1 ts bakepulver",
      "1/2 ts kanel",
      "Smør til steking",
      "Bær og yoghurt til servering",
    ],
    steps: [
      "Mos bananene i en bolle.",
      "Rør inn egg, havregryn, bakepulver og kanel.",
      "La røren hvile i fem minutter.",
      "Stek små pannekaker på middels varme.",
      "Server med bær og yoghurt.",
    ],
  },
  {
    id: 2,
    category: "frokost",
    subcategory: "frokost",
    title: "Helgefrokost med egg",
    description: "Bløtkokte egg, godt brød og en enkel urtesalat.",
    time: "20 min",
    servings: "2 personer",
    difficulty: "Enkel",
    ingredients: [
      "4 egg",
      "4 skiver godt brød",
      "1 håndfull salat",
      "Friske urter",
      "Olivenolje",
      "Salt og pepper",
    ],
    steps: [
      "Kok eggene i 6–7 minutter.",
      "Rist brødskivene lett.",
      "Vend salat og urter med litt olje.",
      "Del eggene og server alt samlet.",
    ],
  },
  {
    id: 3,
    category: "frokost",
    subcategory: "frokost",
    title: "Kjøleskapsgrøt med eple",
    description: "En rolig start på dagen med eple, yoghurt og kardemomme.",
    time: "10 min + hvile",
    servings: "2 glass",
    difficulty: "Enkel",
    ingredients: [
      "2 dl havregryn",
      "2 dl melk",
      "1 dl yoghurt",
      "1 eple",
      "1/2 ts kardemomme",
      "1 ss honning",
    ],
    steps: [
      "Bland havregryn, melk, yoghurt og kardemomme.",
      "Fordel i to glass.",
      "Sett kaldt over natten.",
      "Topp med eple og honning før servering.",
    ],
  },
  {
    id: 4,
    category: "middag",
    subcategory: "fisk",
    title: "Ovnsbakt laks",
    description: "Laks med småpoteter, urter og en frisk sitronkrem.",
    time: "40 min",
    servings: "2 personer",
    difficulty: "Enkel",
    ingredients: [
      "400 g laksefilet",
      "500 g småpoteter",
      "1 sitron",
      "1 dl rømme",
      "Dill",
      "Olivenolje",
      "Salt og pepper",
    ],
    steps: [
      "Sett ovnen på 210 grader.",
      "Bak potetene med olje og salt i 25 minutter.",
      "Legg inn laksen og stek videre i 12–15 minutter.",
      "Bland rømme, sitron og dill.",
      "Server laksen med poteter og sitronkrem.",
    ],
  },
  {
    id: 5,
    category: "middag",
    subcategory: "kylling",
    title: "Kremet kyllinggryte",
    description: "En mild og lun gryte med sopp, timian og sennep.",
    time: "45 min",
    servings: "4 personer",
    difficulty: "Middels",
    ingredients: [
      "600 g kyllingfilet",
      "250 g sopp",
      "1 løk",
      "2 dl matfløte",
      "1 ss dijonsennep",
      "Timian",
      "Salt og pepper",
    ],
    steps: [
      "Brun kyllingen i biter og legg den til side.",
      "Stek løk og sopp mykt.",
      "Ha kyllingen tilbake i pannen.",
      "Tilsett fløte, sennep og timian.",
      "La gryten småkoke i 15 minutter.",
    ],
  },
  {
    id: 6,
    category: "middag",
    subcategory: "svin",
    title: "Svinefilet med eple",
    description: "Saftig svinefilet med epler, salvie og kremet saus.",
    time: "50 min",
    servings: "4 personer",
    difficulty: "Middels",
    ingredients: [
      "700 g svinefilet",
      "2 epler",
      "1 sjalottløk",
      "2 dl fløte",
      "Frisk salvie",
      "Smør",
      "Salt og pepper",
    ],
    steps: [
      "Brun svinefileten godt i smør.",
      "Etterstek i ovn til ønsket kjernetemperatur.",
      "Stek eplebåter og løk i samme panne.",
      "Tilsett fløte og salvie.",
      "Skjær kjøttet i skiver og server med sausen.",
    ],
  },
  {
    id: 7,
    category: "middag",
    subcategory: "biff",
    title: "Biff med peppersaus",
    description: "En klassisk biffmiddag med ovnsbakte grønnsaker.",
    time: "45 min",
    servings: "2 personer",
    difficulty: "Middels",
    ingredients: [
      "2 biffer",
      "1 ss hel pepper",
      "2 dl kremfløte",
      "1 ts soyasaus",
      "Rotgrønnsaker",
      "Smør",
      "Salt",
    ],
    steps: [
      "Bak grønnsakene i ovnen.",
      "Krydre og stek biffene etter ønsket stekegrad.",
      "La kjøttet hvile.",
      "Knus pepper og kok ut pannen med fløte og soyasaus.",
      "Server med grønnsakene.",
    ],
  },
  {
    id: 8,
    category: "middag",
    subcategory: "vegetar",
    title: "Pasta med tomat og burrata",
    description:
      "Enkel pasta med langsomt stekte tomater, hvitløk og basilikum.",
    time: "35 min",
    servings: "2 personer",
    difficulty: "Enkel",
    ingredients: [
      "250 g pasta",
      "400 g cherrytomater",
      "2 hvitløksfedd",
      "1 burrata",
      "Basilikum",
      "Olivenolje",
      "Salt og pepper",
    ],
    steps: [
      "Stek tomater og hvitløk i olje til tomatene faller sammen.",
      "Kok pastaen al dente.",
      "Vend pastaen inn i tomatsausen.",
      "Topp med burrata og basilikum.",
    ],
  },
  {
    id: 9,
    category: "dessert",
    subcategory: "dessert",
    title: "Jordbærkake",
    description: "Lett vaniljekake med krem og friske jordbær.",
    time: "1 t 15 min",
    servings: "8 stykker",
    difficulty: "Middels",
    ingredients: [
      "3 egg",
      "150 g sukker",
      "150 g hvetemel",
      "1 ts bakepulver",
      "3 dl kremfløte",
      "1 kurv jordbær",
      "Vanilje",
    ],
    steps: [
      "Pisk egg og sukker til luftig eggedosis.",
      "Vend inn mel og bakepulver.",
      "Stek bunnen på 175 grader i ca. 30 minutter.",
      "Avkjøl helt.",
      "Topp med pisket krem og jordbær.",
    ],
  },
  {
    id: 10,
    category: "dessert",
    subcategory: "dessert",
    title: "Eplesmuldrepai",
    description: "Varm eplepai med sprø havretopping og vaniljeis.",
    time: "50 min",
    servings: "6 personer",
    difficulty: "Enkel",
    ingredients: [
      "5 epler",
      "1 ts kanel",
      "100 g smør",
      "1,5 dl havregryn",
      "1 dl hvetemel",
      "1 dl brunt sukker",
    ],
    steps: [
      "Skjær eplene og legg dem i en form.",
      "Dryss over kanel.",
      "Smuldre sammen smør, havregryn, mel og sukker.",
      "Fordel toppingen over eplene.",
      "Stek på 190 grader i 30–35 minutter.",
    ],
  },
  {
    id: 11,
    category: "dessert",
    subcategory: "dessert",
    title: "Sitronfromasj",
    description: "Frisk, klassisk og akkurat passe søt.",
    time: "30 min + kjøling",
    servings: "4 glass",
    difficulty: "Middels",
    ingredients: [
      "2 egg",
      "80 g sukker",
      "1 sitron",
      "3 gelatinplater",
      "2 dl kremfløte",
    ],
    steps: [
      "Legg gelatin i kaldt vann.",
      "Pisk egg og sukker luftig.",
      "Varm sitronsaft og løs opp gelatinen.",
      "Vend sitronblandingen inn i eggedosisen.",
      "Vend inn pisket krem og sett kaldt.",
    ],
  },
  {
    id: 12,
    category: "dessert",
    subcategory: "dessert",
    title: "karamellpudding",
    description: "Klassisk karamellpudding med karamellsaus.",
    time: "1 t 30 min",
    servings: "6 personer",
    difficulty: "Middels",
    ingredients: [
      "150 g sukker",
      "5 dl melk",
      "3 egg",
      "1 ts vaniljesukker",
      "Karamellsaus til servering",
    ],
    steps: [
      "Smelt sukker til karamell og hell i form.",
      "Varm melk og vaniljesukker.",
      "Pisk egg og hell i melkeblandingen.",
      "Hell blandingen over karamellen.",
      "Stek i vannbad på 150 grader i ca. 50 minutter.",
    ],
  },
];
